//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg5_practica1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public decimal salario_bruto { get; set; }
        public decimal salario_neto { get; set; }
        public decimal deducciones { get; set; }
    }
}
